# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Source\ Files/string.o"
LINKOBJ  = "Source Files/string.o"
LIBS     = -L"D:/New_folder/Dev-Cpp/MinGW64/lib" -L"D:/New_folder/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/New_folder/Dev-Cpp/MinGW64/include" -I"D:/New_folder/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/New_folder/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/New_folder/Dev-Cpp/MinGW64/include" -I"D:/New_folder/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/New_folder/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/New_folder/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Learning_C_Prog.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"Source\ Files/string.o": Source\ Files/string.c
	$(CPP) -c "Source Files/string.c" -o "Source Files/string.o" $(CXXFLAGS)
